#define GAME_DEFAULT_RESOURCE_PATH "./res/"
#define GAME_DEFAULT_SCRIPT_PATH   "./scripts/"
#define GAME_DEFAULT_SAVE_PATH     "./saves/"
#define GAME_DEFAULT_SCENES_PATH   "./scenes/"
#define GAME_DEFAULT_SHOPS_PATH    "./shops/"
#define GAME_DEFAULT_AREA_PATH     "./areas/"
#define GAME_DEFAULT_DIALOGUE_PATH "./dlg/"

#define GAME_DEFAULT_LOOT_TABLES_FILE    GAME_DEFAULT_RESOURCE_PATH "loot_tables.txt"
#define GAME_DEFAULT_ENTITY_DEF_FILE     GAME_DEFAULT_RESOURCE_PATH "entities.txt"
#define GAME_DEFAULT_ENTITY_ABILITY_FILE GAME_DEFAULT_RESOURCE_PATH "abilities.txt"
#define GAME_DEFAULT_ITEM_FILE           GAME_DEFAULT_RESOURCE_PATH "item_data.txt"
#define GAME_DEFAULT_TILE_DATA_FILE      GAME_DEFAULT_RESOURCE_PATH "tile_data.txt"
/* #define GAME_DEFAULT_STARTUP_FILE        GAME_DEFAULT_RESOURCE_PATH "gamestartup.txt" */
#define GAME_DEFAULT_STARTUP_FILE        "res/" "gamestartup.txt"
