Okay I'll just erase this at the end of each session and write new stuff
into it everytime.

Right now I am:

After that, work on loading cutscene scripts. Which isn't really that complicated, cutscenes are the simplest type of lisp script
as they basically just operate top->down. That's literally all they are. (just gotta code lots of auxiliary functions)

We just need to figure out how to wait on them. Though I suspect it's not too hard.

Then we need to investigate the dialogue system to see how broken it can possibly be at the moment.

After that, we'll start moving our item database into files. We need to do something about other items as well...

After that we'll work on a basic shopping UI. It might become the reference for the new inventory UI, but yeah.

We'll need to add our first entities, so we'll need to draw maybe a few new sprites? We'll just create some entity description
files.


Day end. Day after, we'll see more RPG things to polish I suppose, and we'll add SDL_Mixer audio support (though add arbitrary support
through a simple audio_driver system. Also research on XP/level curves I suppose, we need something balanced. We really should add our first
combat animations and such. That's going to be a little painful?)

All of this should be enough to allow us to prototype the RPG parts of the game.
)


** Might need to move things to more data files
** SDL Mixer Audio
   Too lazy to do real audio mixing (also I don't know how to.)
** Need a normal game UI
** Start writing a GDD
** Add more game "kernel" features
   The core of the game is not done but we're getting closer to
   my revengence
** End Turn
** Also add a game start up script.
** Do we need a world map?
   Probably...
** Draw some new sprites for actors and animals
   Yeah, we need them like now!
** More focused dialogue? Focus on a specific entity
** Weapon and Armor item types
   We need an item equip screen as well, we would also preferably
   draw sprites for each weapon. However, I might avoid that since
   I don't have that capacity...
   
** Party Members
   We need some party member actors, and obviously our new UI
   has to be updated to account for the fact we have new party members.

   Party members will be transferred from their level storage and auto-level?
** Combat First Attacks!
   We need to add ability lists for our characters! They are
   also preferably animated, however that might be a PITA. I might
   have to hard code the animations, I don't have the time to produce
   a full editor UI for animations. So yeah...

   I want it to allow us to have Disgaea Style Animations, so that's
   why I kind of need this to work...

   Each animation is just going to be a unique function. Unfortunately
   that's the best way to do this as animation data otherwise would
   be extraordinarily painful to program in for.

   NOTE the combat is action-points based

   - [ ] Basic Attack!
   - [ ] Skip Turn
   - [ ] Weapon Specific Abilities?! (add Sword, Fist)
     - [ ] Blade Rush    (Sword)
     - [ ] Triple Strike (Fist)

** Fix the word wrap
** Improve the dialogue UI
