Okay I'll just erase this at the end of each session and write new stuff
into it everytime.

Right now I am:

This is going to be quite a bit of work.

So instead of using the kinda serious JRPG story I wanted to do, we're just going to make
a small game about freeing a village from Orcs. It'll be like maybe an hour or two of play or something,
mostly as an engine demo.

** Fix the steering behavior for the pathfinder.
** Also add a game start up script.
** Add level scripts!
** Do we need a world map?
   Probably...
** Draw some new sprites for actors and animals
   Yeah, we need them like now!
** More focused dialogue? Focus on a specific entity
** Cutscene scripting capacity
   Our cutscenes, are really just going to be a product of our scripting system,
   and not a dedicated cutscene system...

   It's a bit of a pain but yeah
** Weapon and Armor item types
   We need an item equip screen as well, we would also preferably
   draw sprites for each weapon. However, I might avoid that since
   I don't have that capacity...
   
** Party Members
   We need some party member actors, and obviously our new UI
   has to be updated to account for the fact we have new party members.

   Party members will be transferred from their level storage and auto-level?
** Combat First Attacks!
   We need to add ability lists for our characters! They are
   also preferably animated, however that might be a PITA. I might
   have to hard code the animations, I don't have the time to produce
   a full editor UI for animations. So yeah...

   I want it to allow us to have Disgaea Style Animations, so that's
   why I kind of need this to work...

   Each animation is just going to be a unique function. Unfortunately
   that's the best way to do this as animation data otherwise would
   be extraordinarily painful to program in for.

   NOTE the combat is action-points based

   - [ ] Basic Attack!
   - [ ] Skip Turn
   - [ ] Weapon Specific Abilities?! (add Sword, Fist)
     - [ ] Blade Rush    (Sword)
     - [ ] Triple Strike (Fist)

** FIx the word wrap
** Improve the dialogue UI
