Okay I'll just erase this at the end of each session and write new stuff
into it everytime.

Right now I am:

Really consider adding that SDL mixer driver since Soloud clearly doesn't fucking work.

Finish that shopping implementation (add the selling menu!)

Start some cutscene stuff. Which isn't really much. We need to author a level for cutscenes...
I'll just try out a march scene to create the constructs that I need.

Introduce objects in the level editor (which are basically preauthored sprite-like structures, they can be collidable.)

Also create the actor table from a list of actor files or something like that. Then I need to draw a few new actor types.

Then work with the combat system to start producing animations, which is probably going to be done using some basic action style
commands, with occasional hard coding.

I want to start the big file packer at some point. Just to make distribution less painful as it would just be one giant binary blob.

Also while this isn't related to this project, I wanna start doing 3D stuff


** Might need to move things to more data files
** SDL Mixer Audio
   Too lazy to do real audio mixing (also I don't know how to.)
** Need a normal game UI
** Start writing a GDD
** Add more game "kernel" features
   The core of the game is not done but we're getting closer to
   my revengence
** End Turn
** Also add a game start up script.
** Do we need a world map?
   Probably...
** Draw some new sprites for actors and animals
   Yeah, we need them like now!
** More focused dialogue? Focus on a specific entity
** Weapon and Armor item types
   We need an item equip screen as well, we would also preferably
   draw sprites for each weapon. However, I might avoid that since
   I don't have that capacity...
   
** Party Members
   We need some party member actors, and obviously our new UI
   has to be updated to account for the fact we have new party members.

   Party members will be transferred from their level storage and auto-level?
** Combat First Attacks!
   We need to add ability lists for our characters! They are
   also preferably animated, however that might be a PITA. I might
   have to hard code the animations, I don't have the time to produce
   a full editor UI for animations. So yeah...

   I want it to allow us to have Disgaea Style Animations, so that's
   why I kind of need this to work...

   Each animation is just going to be a unique function. Unfortunately
   that's the best way to do this as animation data otherwise would
   be extraordinarily painful to program in for.

   NOTE the combat is action-points based

   - [ ] Basic Attack!
   - [ ] Skip Turn
   - [ ] Weapon Specific Abilities?! (add Sword, Fist)
     - [ ] Blade Rush    (Sword)
     - [ ] Triple Strike (Fist)

** Fix the word wrap
** Improve the dialogue UI
